# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('coiffure_homme', 'Coiffure homme'), ('coiffure_femme', 'Coiffure femme'), ('esthetique', 'Esthétique'), ('pedicure', 'Pédicure'), ('manucure', 'Manucure'), ('autre', 'Autre')], max_length=30)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_estimee_minutes', models.PositiveIntegerField(default=30)),
                ('actif', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='salons.salon')),
            ],
        ),
    ]
