# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^\\+?[0-9]{8,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('langue_preferee', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('zone_geographique', models.CharField(blank=True, help_text='Détectée automatiquement (pays/région) pour adapter la langue par défaut.', max_length=100, null=True)),
                ('est_admin_principal', models.BooleanField(default=False)),
                ('est_admin_secondaire', models.BooleanField(default=False)),
                ('mot_de_passe_temporaire', models.BooleanField(default=False, help_text="Vrai quand le compte a été créé par un gestionnaire pour un employé : l'utilisateur doit changer son mot de passe à sa première connexion.")),
                ('a_utilise_essai_gratuit', models.BooleanField(default=False, help_text="Un utilisateur ne peut bénéficier de l'essai gratuit de 14 jours que sur le tout premier salon qu'il crée, même s'il crée ensuite d'autres salons.")),
                ('photo_url', models.URLField(blank=True, help_text="Photo de profil. Stockée en tant qu'URL (voir README pour le stockage objet à brancher).", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DroitAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_modifier_salon', models.BooleanField(default=False)),
                ('peut_ajouter_administrateur', models.BooleanField(default=False)),
                ('peut_creer_codes_reduction', models.BooleanField(default=False)),
                ('peut_creer_codes_sponsoring', models.BooleanField(default=False)),
                ('peut_voir_abonnements', models.BooleanField(default=False)),
                ('peut_consulter_rendement_employes', models.BooleanField(default=False)),
                ('peut_consulter_depenses', models.BooleanField(default=False)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('administrateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='droits', to=settings.AUTH_USER_MODEL)),
                ('attribue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droits_attribues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
