# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementAnalyseSectorielle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_abonnement', models.CharField(choices=[('secteurs_rentables', 'Analyse des secteurs rentables (20000)'), ('gestion_complete', 'Analyse de gestion complète (25000)')], max_length=30)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_analyse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeReduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('montant_reduction', models.DecimalField(decimal_places=2, help_text='Montant fixe (en FCFA) déduit du montant total, et non un pourcentage.', max_digits=10)),
                ('proprietaire_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('proprietaire_contact', models.CharField(blank=True, help_text='Email ou téléphone du propriétaire du code.', max_length=150, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('nombre_utilisations_max', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_utilisations', models.PositiveIntegerField(default=0, help_text='Compteur incrémenté à chaque abonnement souscrit avec ce code.')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSponsoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('beneficiaire_nom', models.CharField(max_length=150)),
                ('beneficiaire_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_reduction_utilisateur', models.DecimalField(decimal_places=2, default=0, help_text="Montant fixe (en FCFA) déduit du montant total de l'abonnement pour la personne qui utilise ce code à la souscription/au renouvellement — distinct de la commission versée au propriétaire du code.", max_digits=10)),
                ('est_partenaire_employe', models.BooleanField(default=False)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_fixe_par_utilisation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre_utilisations', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_attente_paiement', 'En attente de paiement')], default='actif', max_length=25)),
                ('mode_paiement', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('carte_bancaire', 'Carte bancaire')], max_length=20, null=True)),
                ('date_paiement_confirme', models.DateTimeField(blank=True, null=True)),
                ('beneficiaire_utilisateur', models.ForeignKey(blank=True, help_text='Renseigné uniquement pour les codes achetés via le programme partenaire employé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_sponsoring_achetes', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_sponsoring_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_forfait', models.CharField(choices=[('abonnement_salon', 'Abonnement salon'), ('analyse_sectorielle', 'Analyse sectorielle'), ('autre', 'Autre')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_mois', models.PositiveSmallIntegerField(blank=True, help_text="Laisser vide si le forfait n'est pas périodique (ex. analyse sectorielle).", null=True)),
                ('avantages', models.JSONField(blank=True, default=list, help_text='Liste de courtes phrases affichées comme avantages sur la landing page.')),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfaits_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordre_affichage', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('nombre_employes_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('secteur_geographique', models.CharField(help_text='Quartier / secteur utilisé pour les statistiques par zone.', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('en_attente', 'En attente de paiement')], default='en_attente', max_length=20)),
                ('nom_modifiable', models.BooleanField(default=True, help_text="Devient faux dès que le propriétaire a renommé le salon une fois après sa création — le nom n'est alors plus modifiable via l'API.")),
                ('photo_url', models.TextField(blank=True, help_text="Photo du salon : soit une URL externe, soit une image encodée en base64 (data:image/...;base64,...) envoyée directement depuis le formulaire d'upload du frontend. Un TextField plutôt qu'un URLField pour accepter les deux cas — voir README pour un branchement vers un vrai stockage objet (S3/Cloudinary) en production à grande échelle.", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salons_possedes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('est_premier_abonnement', models.BooleanField(default=False)),
                ('est_essai', models.BooleanField(default=False, help_text='Essai gratuit de 14 jours, sans paiement ni carte bancaire, limité à un par salon.')),
                ('duree_mois', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('code_reduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements', to='salons.codereduction')),
                ('code_sponsoring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements', to='salons.codesponsoring')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='salons.salon')),
            ],
        ),
    ]
