# Generated by Django 5.0.7 on 2026-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='est_essai',
            field=models.BooleanField(default=False, help_text='Essai gratuit de 15 jours, sans paiement ni carte bancaire, limité à un par salon.'),
        ),
    ]
