# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('motif', models.CharField(choices=[('partenariat', 'Devenir partenaire'), ('ouverture_salon', 'Ouvrir un salon'), ('information', "Prise d'information"), ('autre', 'Autre')], default='information', max_length=30)),
                ('message', models.TextField()),
                ('traite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCodePromo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_origine', to='salons.codereduction')),
            ],
        ),
        migrations.CreateModel(
            name='DemandePartenariat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('structure', models.CharField(blank=True, max_length=150, null=True)),
                ('contact', models.CharField(help_text='Email ou téléphone du demandeur.', max_length=150)),
                ('traite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('code_sponsoring_attribue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='salons.codesponsoring')),
            ],
        ),
    ]
