# Generated by Django 5.0.7 on 2026-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecteurGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
            ],
        ),
    ]
