# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('coiffeur_homme', 'Coiffeur homme'), ('coiffeuse_femme', 'Coiffeuse femme'), ('caissiere', 'Caissière'), ('maquilleuse', 'Maquilleuse'), ('estheticienne', 'Esthéticienne'), ('gestionnaire', 'Gestionnaire du salon'), ('autre', 'Autre')], max_length=30)),
                ('role_autre_precision', models.CharField(blank=True, help_text="Précision du rôle si 'Autre' est sélectionné.", max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('peut_creer_ticket', models.BooleanField(default=True)),
                ('peut_confirmer_ticket', models.BooleanField(default=True)),
                ('peut_valider_ticket', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='salons.salon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'salon')},
            },
        ),
    ]
