# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('materiel', 'Matériel'), ('produit_homme', 'Produit homme'), ('produit_femme', 'Produit femme'), ('esthetique', 'Esthétique'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5, help_text='En dessous de ce seuil, une alerte de rupture est envoyée.')),
                ('prix_unitaire_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_dernier_achat', models.DateField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('achat', 'Achat / réapprovisionnement'), ('consommation', 'Consommation (soin exécuté)'), ('ajustement', 'Ajustement manuel')], max_length=20)),
                ('quantite', models.IntegerField(help_text='Positif pour un achat, négatif pour une consommation.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ticket_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='tickets.ticket')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stocks.produit')),
            ],
        ),
    ]
