# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanJournalierSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entrees_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrees_coiffure_homme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrees_coiffure_femme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrees_esthetique', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrees_pedicure', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrees_manucure', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entrees_autre', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('depenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_journaliers', to='salons.salon')),
            ],
            options={
                'unique_together': {('salon', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RendementEmployeJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre_soins', models.PositiveIntegerField(default=0)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendements_journaliers', to='employes.employe')),
            ],
            options={
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
