# Generated by Django 5.0.7 on 2026-09-08 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employes', '0001_initial'),
        ('salons', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_client_temporaire', models.CharField(blank=True, help_text="Utilisé si le client n'existe pas encore en base.", max_length=150, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('valide', 'Validé / payé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('carte_bancaire', 'Carte bancaire')], max_length=20, null=True)),
                ('reduction_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_brut', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('caissiere_validatrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_valides', to='employes.employe')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='clients.client')),
                ('employe_createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_crees', to='employes.employe')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='LigneTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé (soin réalisé)'), ('annule', 'Annulé (client absent/annulation)')], default='en_attente', max_length=20)),
                ('employe_executant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soins_a_executer', to='employes.employe')),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ticket', to='services.soin')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='tickets.ticket')),
            ],
        ),
    ]
